[I 2023-12-26 13:41:25,642] Using an existing study with name 'GCNConv' instead of creating a new one.
/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
[W 2023-12-26 13:50:30,535] Trial 2 failed with parameters: {'batch_size': 50, 'drug_hidden': 64, 'protein_hidden': 64, 'dropout': 0.1, 'is_attention': True, 'lr': 0.01, 'epochs': 100} because of the following error: RuntimeError('mat1 and mat2 shapes cannot be multiplied (30002x1280 and 5x64)').
Traceback (most recent call last):
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/panfs/jay/groups/33/kuangr/inoue019/Dual3DDTI/exp_stitch/pdb_GCNConv.py", line 259, in objective
    output = model(drug, protein)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/panfs/jay/groups/33/kuangr/inoue019/Dual3DDTI/exp_stitch/pdb_GCNConv.py", line 139, in forward
    x_protein = self.protein_encoder(protein_data)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/panfs/jay/groups/33/kuangr/inoue019/Dual3DDTI/exp_stitch/pdb_GCNConv.py", line 111, in forward
    x = self.conv1(x, edge_index)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 229, in forward
    x = self.lin(x)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch_geometric/nn/dense/linear.py", line 132, in forward
    return F.linear(x, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (30002x1280 and 5x64)
[W 2023-12-26 13:50:30,559] Trial 2 failed with value None.
Train dim: (24964, 3)
val dim: (3531, 3)
test dim: (7169, 3)
Traceback (most recent call last):
  File "/panfs/jay/groups/33/kuangr/inoue019/Dual3DDTI/exp_stitch/pdb_GCNConv.py", line 296, in <module>
    study.optimize(objective, n_trials=1000, gc_after_trial=True)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/optuna/study/study.py", line 442, in optimize
    _optimize(
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/panfs/jay/groups/33/kuangr/inoue019/Dual3DDTI/exp_stitch/pdb_GCNConv.py", line 259, in objective
    output = model(drug, protein)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/panfs/jay/groups/33/kuangr/inoue019/Dual3DDTI/exp_stitch/pdb_GCNConv.py", line 139, in forward
    x_protein = self.protein_encoder(protein_data)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/panfs/jay/groups/33/kuangr/inoue019/Dual3DDTI/exp_stitch/pdb_GCNConv.py", line 111, in forward
    x = self.conv1(x, edge_index)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 229, in forward
    x = self.lin(x)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/torch_geometric/nn/dense/linear.py", line 132, in forward
    return F.linear(x, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (30002x1280 and 5x64)
